#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 30G # 20GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o ./out/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e ./out/%x_%u_%j.err # File to which STDERR will be written
#SBATCH --job-name=demo

nvidia-smi
export CUDA_LAUNCH_BLOCKING=1

# BE CAREFUL! GUARDA ELS RESULTATS AL MATEIX DIRECTORY I HO SOBRESCRIU, ES RARU

SESSION=1
EPOCH=20
CHECKPOINT=10021

python demo.py --net res101 \
               --checksession $SESSION --checkepoch $EPOCH --checkpoint $CHECKPOINT \
               --cuda --load_dir models/

