#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 30G # 20GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o ./out/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e ./out/%x_%u_%j.err # File to which STDERR will be written
#SBATCH --job-name=pascal_res101


nvidia-smi
export CUDA_LAUNCH_BLOCKING=1

LEARNING_RATE=4e-3
BATCH_SIZE=4
DECAY_STEP=8

python3 trainval_net.py --dataset pascal_voc --net res101 \
                       --bs $BATCH_SIZE --nw 1 \
                       --lr $LEARNING_RATE --lr_decay_step $DECAY_STEP \
                       --cuda --mGPUs --epochs 20
